[env:xiaoble]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-afruitnrf52-nrf52840
framework = arduino

monitor_speed = 115200
lib_archive = no

build_flags =
  -I include
  -DUSE_TINYUSB
  -DDEBUG_LOGGING
  -g3

lib_deps =
  adafruit/Adafruit TinyUSB Library
  adafruit/Adafruit LIS3DH
  adafruit/Adafruit Unified Sensor


